# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        main:
            entity:
                class: AppBundle\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout

    access_control:
        - path: ^/$
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/(en|fr)/$
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/(en|fr)/login$
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/(en|fr)/userregister$
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/(en|fr)/adminregister$
          roles: IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/(en|fr)/admin*
          roles: ROLE_ADMIN
        - path: ^/
          roles: ROLE_USER
